//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int applicantId { get; set; }
        public int educationId { get; set; }
        public string nameAddress { get; set; }
        public string yearsAttended { get; set; }
        public string graduated { get; set; }
        public string degreeMajor { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
