//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.AvailablePositions = new HashSet<AvailablePosition>();
        }
    
        public int positionId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string pay { get; set; }
    
        public virtual ICollection<AvailablePosition> AvailablePositions { get; set; }
        public virtual Questionaire Questionaire { get; set; }
    }
}
