//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Questionaires = new HashSet<Questionaire>();
        }
    
        public int questionId { get; set; }
        public string theQuestion { get; set; }
        public string theAnswer { get; set; }
    
        public virtual ICollection<Questionaire> Questionaires { get; set; }
    }
}
