//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionaire
    {
        public int questionaireId { get; set; }
        public int questionId { get; set; }
        public int positionId { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Question Question { get; set; }
    }
}
