//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int applicantId { get; set; }
        public int referenceId { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string company { get; set; }
        public string title { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
