//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Applications = new HashSet<Application>();
            this.AvailablePositions = new HashSet<AvailablePosition>();
        }
    
        public int storeId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string stateAbbreviation { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<AvailablePosition> AvailablePositions { get; set; }
    }
}
