//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESApplications.AppServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jAvailPosIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jAvailPosId {
            get {
                return this.jAvailPosIdField;
            }
            set {
                if ((this.jAvailPosIdField.Equals(value) != true)) {
                    this.jAvailPosIdField = value;
                    this.RaisePropertyChanged("jAvailPosId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jDays {
            get {
                return this.jDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.jDaysField, value) != true)) {
                    this.jDaysField = value;
                    this.RaisePropertyChanged("jDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jDescription {
            get {
                return this.jDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.jDescriptionField, value) != true)) {
                    this.jDescriptionField = value;
                    this.RaisePropertyChanged("jDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jLocation {
            get {
                return this.jLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.jLocationField, value) != true)) {
                    this.jLocationField = value;
                    this.RaisePropertyChanged("jLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jPay {
            get {
                return this.jPayField;
            }
            set {
                if ((object.ReferenceEquals(this.jPayField, value) != true)) {
                    this.jPayField = value;
                    this.RaisePropertyChanged("jPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jTitle {
            get {
                return this.jTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.jTitleField, value) != true)) {
                    this.jTitleField = value;
                    this.RaisePropertyChanged("jTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Application[] ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.AvailablePosition[] AvailablePositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateAbbreviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Application[] Applications {
            get {
                return this.ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationsField, value) != true)) {
                    this.ApplicationsField = value;
                    this.RaisePropertyChanged("Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.AvailablePosition[] AvailablePositions {
            get {
                return this.AvailablePositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailablePositionsField, value) != true)) {
                    this.AvailablePositionsField = value;
                    this.RaisePropertyChanged("AvailablePositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateAbbreviation {
            get {
                return this.stateAbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.stateAbbreviationField, value) != true)) {
                    this.stateAbbreviationField = value;
                    this.RaisePropertyChanged("stateAbbreviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Application", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Application : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.AvailablePosition AvailablePositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.PersonalInfo PersonalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int applicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int availablePosIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.AvailablePosition AvailablePosition {
            get {
                return this.AvailablePositionField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailablePositionField, value) != true)) {
                    this.AvailablePositionField = value;
                    this.RaisePropertyChanged("AvailablePosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.PersonalInfo PersonalInfo {
            get {
                return this.PersonalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalInfoField, value) != true)) {
                    this.PersonalInfoField = value;
                    this.RaisePropertyChanged("PersonalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantId {
            get {
                return this.applicantIdField;
            }
            set {
                if ((this.applicantIdField.Equals(value) != true)) {
                    this.applicantIdField = value;
                    this.RaisePropertyChanged("applicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int availablePosId {
            get {
                return this.availablePosIdField;
            }
            set {
                if ((this.availablePosIdField.Equals(value) != true)) {
                    this.availablePosIdField = value;
                    this.RaisePropertyChanged("availablePosId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailablePosition", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class AvailablePosition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Application[] ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Position PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int availablePosIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string workingDaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Application[] Applications {
            get {
                return this.ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationsField, value) != true)) {
                    this.ApplicationsField = value;
                    this.RaisePropertyChanged("Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Position Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int availablePosId {
            get {
                return this.availablePosIdField;
            }
            set {
                if ((this.availablePosIdField.Equals(value) != true)) {
                    this.availablePosIdField = value;
                    this.RaisePropertyChanged("availablePosId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int positionId {
            get {
                return this.positionIdField;
            }
            set {
                if ((this.positionIdField.Equals(value) != true)) {
                    this.positionIdField = value;
                    this.RaisePropertyChanged("positionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workingDays {
            get {
                return this.workingDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.workingDaysField, value) != true)) {
                    this.workingDaysField = value;
                    this.RaisePropertyChanged("workingDays");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class PersonalInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Application[] ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Education[] EducationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.ElectronicSig ElectronicSigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.JobHistory[] JobHistoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Reference[] ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int applicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string socialNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Application[] Applications {
            get {
                return this.ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationsField, value) != true)) {
                    this.ApplicationsField = value;
                    this.RaisePropertyChanged("Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Education[] Educations {
            get {
                return this.EducationsField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationsField, value) != true)) {
                    this.EducationsField = value;
                    this.RaisePropertyChanged("Educations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.ElectronicSig ElectronicSig {
            get {
                return this.ElectronicSigField;
            }
            set {
                if ((object.ReferenceEquals(this.ElectronicSigField, value) != true)) {
                    this.ElectronicSigField = value;
                    this.RaisePropertyChanged("ElectronicSig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.JobHistory[] JobHistories {
            get {
                return this.JobHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.JobHistoriesField, value) != true)) {
                    this.JobHistoriesField = value;
                    this.RaisePropertyChanged("JobHistories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Reference[] References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.aliasField, value) != true)) {
                    this.aliasField = value;
                    this.RaisePropertyChanged("alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantId {
            get {
                return this.applicantIdField;
            }
            set {
                if ((this.applicantIdField.Equals(value) != true)) {
                    this.applicantIdField = value;
                    this.RaisePropertyChanged("applicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string socialNum {
            get {
                return this.socialNumField;
            }
            set {
                if ((object.ReferenceEquals(this.socialNumField, value) != true)) {
                    this.socialNumField = value;
                    this.RaisePropertyChanged("socialNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.AvailablePosition[] AvailablePositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Questionaire QuestionaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.AvailablePosition[] AvailablePositions {
            get {
                return this.AvailablePositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailablePositionsField, value) != true)) {
                    this.AvailablePositionsField = value;
                    this.RaisePropertyChanged("AvailablePositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Questionaire Questionaire {
            get {
                return this.QuestionaireField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionaireField, value) != true)) {
                    this.QuestionaireField = value;
                    this.RaisePropertyChanged("Questionaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pay {
            get {
                return this.payField;
            }
            set {
                if ((object.ReferenceEquals(this.payField, value) != true)) {
                    this.payField = value;
                    this.RaisePropertyChanged("pay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int positionId {
            get {
                return this.positionIdField;
            }
            set {
                if ((this.positionIdField.Equals(value) != true)) {
                    this.positionIdField = value;
                    this.RaisePropertyChanged("positionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questionaire", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Questionaire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Position PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Question QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int questionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int questionaireIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Position Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Question Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int positionId {
            get {
                return this.positionIdField;
            }
            set {
                if ((this.positionIdField.Equals(value) != true)) {
                    this.positionIdField = value;
                    this.RaisePropertyChanged("positionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionId {
            get {
                return this.questionIdField;
            }
            set {
                if ((this.questionIdField.Equals(value) != true)) {
                    this.questionIdField = value;
                    this.RaisePropertyChanged("questionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionaireId {
            get {
                return this.questionaireIdField;
            }
            set {
                if ((this.questionaireIdField.Equals(value) != true)) {
                    this.questionaireIdField = value;
                    this.RaisePropertyChanged("questionaireId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Questionaire[] QuestionairesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int questionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string theAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string theQuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Questionaire[] Questionaires {
            get {
                return this.QuestionairesField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionairesField, value) != true)) {
                    this.QuestionairesField = value;
                    this.RaisePropertyChanged("Questionaires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionId {
            get {
                return this.questionIdField;
            }
            set {
                if ((this.questionIdField.Equals(value) != true)) {
                    this.questionIdField = value;
                    this.RaisePropertyChanged("questionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string theAnswer {
            get {
                return this.theAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.theAnswerField, value) != true)) {
                    this.theAnswerField = value;
                    this.RaisePropertyChanged("theAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string theQuestion {
            get {
                return this.theQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.theQuestionField, value) != true)) {
                    this.theQuestionField = value;
                    this.RaisePropertyChanged("theQuestion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectronicSig", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ElectronicSig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.PersonalInfo PersonalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int applicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.PersonalInfo PersonalInfo {
            get {
                return this.PersonalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalInfoField, value) != true)) {
                    this.PersonalInfoField = value;
                    this.RaisePropertyChanged("PersonalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantId {
            get {
                return this.applicantIdField;
            }
            set {
                if ((this.applicantIdField.Equals(value) != true)) {
                    this.applicantIdField = value;
                    this.RaisePropertyChanged("applicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Education", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Education : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.PersonalInfo PersonalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int applicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string degreeMajorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int educationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string graduatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearsAttendedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.PersonalInfo PersonalInfo {
            get {
                return this.PersonalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalInfoField, value) != true)) {
                    this.PersonalInfoField = value;
                    this.RaisePropertyChanged("PersonalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantId {
            get {
                return this.applicantIdField;
            }
            set {
                if ((this.applicantIdField.Equals(value) != true)) {
                    this.applicantIdField = value;
                    this.RaisePropertyChanged("applicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string degreeMajor {
            get {
                return this.degreeMajorField;
            }
            set {
                if ((object.ReferenceEquals(this.degreeMajorField, value) != true)) {
                    this.degreeMajorField = value;
                    this.RaisePropertyChanged("degreeMajor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int educationId {
            get {
                return this.educationIdField;
            }
            set {
                if ((this.educationIdField.Equals(value) != true)) {
                    this.educationIdField = value;
                    this.RaisePropertyChanged("educationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string graduated {
            get {
                return this.graduatedField;
            }
            set {
                if ((object.ReferenceEquals(this.graduatedField, value) != true)) {
                    this.graduatedField = value;
                    this.RaisePropertyChanged("graduated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameAddress {
            get {
                return this.nameAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.nameAddressField, value) != true)) {
                    this.nameAddressField = value;
                    this.RaisePropertyChanged("nameAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yearsAttended {
            get {
                return this.yearsAttendedField;
            }
            set {
                if ((object.ReferenceEquals(this.yearsAttendedField, value) != true)) {
                    this.yearsAttendedField = value;
                    this.RaisePropertyChanged("yearsAttended");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobHistory", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class JobHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.PersonalInfo PersonalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int applicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dutiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jobHistoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonLeaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string supervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> toField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.PersonalInfo PersonalInfo {
            get {
                return this.PersonalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalInfoField, value) != true)) {
                    this.PersonalInfoField = value;
                    this.RaisePropertyChanged("PersonalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantId {
            get {
                return this.applicantIdField;
            }
            set {
                if ((this.applicantIdField.Equals(value) != true)) {
                    this.applicantIdField = value;
                    this.RaisePropertyChanged("applicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string duties {
            get {
                return this.dutiesField;
            }
            set {
                if ((object.ReferenceEquals(this.dutiesField, value) != true)) {
                    this.dutiesField = value;
                    this.RaisePropertyChanged("duties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employer {
            get {
                return this.employerField;
            }
            set {
                if ((object.ReferenceEquals(this.employerField, value) != true)) {
                    this.employerField = value;
                    this.RaisePropertyChanged("employer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endSalary {
            get {
                return this.endSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.endSalaryField, value) != true)) {
                    this.endSalaryField = value;
                    this.RaisePropertyChanged("endSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> from {
            get {
                return this.fromField;
            }
            set {
                if ((this.fromField.Equals(value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jobHistoryId {
            get {
                return this.jobHistoryIdField;
            }
            set {
                if ((this.jobHistoryIdField.Equals(value) != true)) {
                    this.jobHistoryIdField = value;
                    this.RaisePropertyChanged("jobHistoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reasonLeave {
            get {
                return this.reasonLeaveField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonLeaveField, value) != true)) {
                    this.reasonLeaveField = value;
                    this.RaisePropertyChanged("reasonLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startSalary {
            get {
                return this.startSalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.startSalaryField, value) != true)) {
                    this.startSalaryField = value;
                    this.RaisePropertyChanged("startSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string supervisor {
            get {
                return this.supervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.supervisorField, value) != true)) {
                    this.supervisorField = value;
                    this.RaisePropertyChanged("supervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> to {
            get {
                return this.toField;
            }
            set {
                if ((this.toField.Equals(value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reference", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Reference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.PersonalInfo PersonalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int applicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int referenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.PersonalInfo PersonalInfo {
            get {
                return this.PersonalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalInfoField, value) != true)) {
                    this.PersonalInfoField = value;
                    this.RaisePropertyChanged("PersonalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantId {
            get {
                return this.applicantIdField;
            }
            set {
                if ((this.applicantIdField.Equals(value) != true)) {
                    this.applicantIdField = value;
                    this.RaisePropertyChanged("applicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int referenceId {
            get {
                return this.referenceIdField;
            }
            set {
                if ((this.referenceIdField.Equals(value) != true)) {
                    this.referenceIdField = value;
                    this.RaisePropertyChanged("referenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicantApp", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ApplicantApp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Education educationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.ElectronicSig electronicSigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.JobHistory jobHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.PersonalInfo personalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AESApplications.AppServiceReference.Reference referenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Education education {
            get {
                return this.educationField;
            }
            set {
                if ((object.ReferenceEquals(this.educationField, value) != true)) {
                    this.educationField = value;
                    this.RaisePropertyChanged("education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.ElectronicSig electronicSig {
            get {
                return this.electronicSigField;
            }
            set {
                if ((object.ReferenceEquals(this.electronicSigField, value) != true)) {
                    this.electronicSigField = value;
                    this.RaisePropertyChanged("electronicSig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.JobHistory jobHistory {
            get {
                return this.jobHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.jobHistoryField, value) != true)) {
                    this.jobHistoryField = value;
                    this.RaisePropertyChanged("jobHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.PersonalInfo personalInfo {
            get {
                return this.personalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.personalInfoField, value) != true)) {
                    this.personalInfoField = value;
                    this.RaisePropertyChanged("personalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AESApplications.AppServiceReference.Reference reference {
            get {
                return this.referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField, value) != true)) {
                    this.referenceField = value;
                    this.RaisePropertyChanged("reference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppServiceReference.IAppService")]
    public interface IAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getJobs", ReplyAction="http://tempuri.org/IAppService/getJobsResponse")]
        AESApplications.AppServiceReference.Job[] getJobs(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getJobs", ReplyAction="http://tempuri.org/IAppService/getJobsResponse")]
        System.Threading.Tasks.Task<AESApplications.AppServiceReference.Job[]> getJobsAsync(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getStoreInfo", ReplyAction="http://tempuri.org/IAppService/getStoreInfoResponse")]
        AESApplications.AppServiceReference.Store getStoreInfo(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getStoreInfo", ReplyAction="http://tempuri.org/IAppService/getStoreInfoResponse")]
        System.Threading.Tasks.Task<AESApplications.AppServiceReference.Store> getStoreInfoAsync(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getQuestions", ReplyAction="http://tempuri.org/IAppService/getQuestionsResponse")]
        AESApplications.AppServiceReference.Question[] getQuestions(int[] positionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getQuestions", ReplyAction="http://tempuri.org/IAppService/getQuestionsResponse")]
        System.Threading.Tasks.Task<AESApplications.AppServiceReference.Question[]> getQuestionsAsync(int[] positionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storePersonalInfo", ReplyAction="http://tempuri.org/IAppService/storePersonalInfoResponse")]
        int storePersonalInfo(AESApplications.AppServiceReference.PersonalInfo personalInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storePersonalInfo", ReplyAction="http://tempuri.org/IAppService/storePersonalInfoResponse")]
        System.Threading.Tasks.Task<int> storePersonalInfoAsync(AESApplications.AppServiceReference.PersonalInfo personalInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeEducations", ReplyAction="http://tempuri.org/IAppService/storeEducationsResponse")]
        bool storeEducations(AESApplications.AppServiceReference.Education[] educations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeEducations", ReplyAction="http://tempuri.org/IAppService/storeEducationsResponse")]
        System.Threading.Tasks.Task<bool> storeEducationsAsync(AESApplications.AppServiceReference.Education[] educations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeJobHistory", ReplyAction="http://tempuri.org/IAppService/storeJobHistoryResponse")]
        bool storeJobHistory(AESApplications.AppServiceReference.JobHistory[] jobHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeJobHistory", ReplyAction="http://tempuri.org/IAppService/storeJobHistoryResponse")]
        System.Threading.Tasks.Task<bool> storeJobHistoryAsync(AESApplications.AppServiceReference.JobHistory[] jobHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeReferences", ReplyAction="http://tempuri.org/IAppService/storeReferencesResponse")]
        bool storeReferences(AESApplications.AppServiceReference.Reference[] reference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeReferences", ReplyAction="http://tempuri.org/IAppService/storeReferencesResponse")]
        System.Threading.Tasks.Task<bool> storeReferencesAsync(AESApplications.AppServiceReference.Reference[] reference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeElectronicSig", ReplyAction="http://tempuri.org/IAppService/storeElectronicSigResponse")]
        bool storeElectronicSig(AESApplications.AppServiceReference.ElectronicSig electronicSig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/storeElectronicSig", ReplyAction="http://tempuri.org/IAppService/storeElectronicSigResponse")]
        System.Threading.Tasks.Task<bool> storeElectronicSigAsync(AESApplications.AppServiceReference.ElectronicSig electronicSig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getApplication", ReplyAction="http://tempuri.org/IAppService/getApplicationResponse")]
        AESApplications.AppServiceReference.ApplicantApp getApplication(int appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppService/getApplication", ReplyAction="http://tempuri.org/IAppService/getApplicationResponse")]
        System.Threading.Tasks.Task<AESApplications.AppServiceReference.ApplicantApp> getApplicationAsync(int appId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppServiceChannel : AESApplications.AppServiceReference.IAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppServiceClient : System.ServiceModel.ClientBase<AESApplications.AppServiceReference.IAppService>, AESApplications.AppServiceReference.IAppService {
        
        public AppServiceClient() {
        }
        
        public AppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AESApplications.AppServiceReference.Job[] getJobs(int storeId) {
            return base.Channel.getJobs(storeId);
        }
        
        public System.Threading.Tasks.Task<AESApplications.AppServiceReference.Job[]> getJobsAsync(int storeId) {
            return base.Channel.getJobsAsync(storeId);
        }
        
        public AESApplications.AppServiceReference.Store getStoreInfo(int storeId) {
            return base.Channel.getStoreInfo(storeId);
        }
        
        public System.Threading.Tasks.Task<AESApplications.AppServiceReference.Store> getStoreInfoAsync(int storeId) {
            return base.Channel.getStoreInfoAsync(storeId);
        }
        
        public AESApplications.AppServiceReference.Question[] getQuestions(int[] positionIds) {
            return base.Channel.getQuestions(positionIds);
        }
        
        public System.Threading.Tasks.Task<AESApplications.AppServiceReference.Question[]> getQuestionsAsync(int[] positionIds) {
            return base.Channel.getQuestionsAsync(positionIds);
        }
        
        public int storePersonalInfo(AESApplications.AppServiceReference.PersonalInfo personalInfo) {
            return base.Channel.storePersonalInfo(personalInfo);
        }
        
        public System.Threading.Tasks.Task<int> storePersonalInfoAsync(AESApplications.AppServiceReference.PersonalInfo personalInfo) {
            return base.Channel.storePersonalInfoAsync(personalInfo);
        }
        
        public bool storeEducations(AESApplications.AppServiceReference.Education[] educations) {
            return base.Channel.storeEducations(educations);
        }
        
        public System.Threading.Tasks.Task<bool> storeEducationsAsync(AESApplications.AppServiceReference.Education[] educations) {
            return base.Channel.storeEducationsAsync(educations);
        }
        
        public bool storeJobHistory(AESApplications.AppServiceReference.JobHistory[] jobHistory) {
            return base.Channel.storeJobHistory(jobHistory);
        }
        
        public System.Threading.Tasks.Task<bool> storeJobHistoryAsync(AESApplications.AppServiceReference.JobHistory[] jobHistory) {
            return base.Channel.storeJobHistoryAsync(jobHistory);
        }
        
        public bool storeReferences(AESApplications.AppServiceReference.Reference[] reference) {
            return base.Channel.storeReferences(reference);
        }
        
        public System.Threading.Tasks.Task<bool> storeReferencesAsync(AESApplications.AppServiceReference.Reference[] reference) {
            return base.Channel.storeReferencesAsync(reference);
        }
        
        public bool storeElectronicSig(AESApplications.AppServiceReference.ElectronicSig electronicSig) {
            return base.Channel.storeElectronicSig(electronicSig);
        }
        
        public System.Threading.Tasks.Task<bool> storeElectronicSigAsync(AESApplications.AppServiceReference.ElectronicSig electronicSig) {
            return base.Channel.storeElectronicSigAsync(electronicSig);
        }
        
        public AESApplications.AppServiceReference.ApplicantApp getApplication(int appId) {
            return base.Channel.getApplication(appId);
        }
        
        public System.Threading.Tasks.Task<AESApplications.AppServiceReference.ApplicantApp> getApplicationAsync(int appId) {
            return base.Channel.getApplicationAsync(appId);
        }
    }
}
