//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAppServiceLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobHistory
    {
        public int applicantId { get; set; }
        public string employer { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string supervisor { get; set; }
        public string position { get; set; }
        public string startSalary { get; set; }
        public string endSalary { get; set; }
        public string reasonLeave { get; set; }
        public string duties { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
